environments:

- name: dev
  services:
    - name: nginx-a
      helmValuesFile: values/dev-values.yaml
    - name: nginx-b
      helmValuesFile: values/dev-values.yaml



- name: brian
  services:
    - name: nginx-a
      helmValuesFile: values/brian-values.yaml