environments:

- name: dev
  services:
    - name: nginx-a
      helmValues:
        replicaCount: 1
    - name: nginx-b
      helmValues:
        replicaCount: 1


- name: brian
  services:
    - name: nginx-a
      helmValues:
        replicaCount: 1