environments:

- name: dev
  services:
    - name: nginx-a
      helmValues:
        replicaCount: 2
        namespace: dev
    - name: nginx-b
      helmValues:
        replicaCount: 1
        namespace: dev


- name: brian
  services:
    - name: nginx-a
      helmValues:
        namespace: brian
        replicaCount: 1