environments:
  - name: dev
    host: dev.example.com
    replicaCount: 1
    helmValuesFile: values/dev-values.yaml
    services:
      - name: nginx-a
      - name: nginx-b
  - name: brian
    host: brian.example.com
    replicaCount: 2
    helmValuesFile: values/brian-values.yaml
    services:
      - name: nginx-a