{{- range $configmap := .Values.configmaps }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  namespace: {{ $.Values.namespace }}
data:
  {{- range $key, $val  := $configmap.data }}
  {{ $key }} : "{{ $val }}"
  {{- end }}
{{- end }}