
{{- $configmaps := merge .Values.configmaps .Values.overrides.configmaps }}

{{- range $configMapName, $configMapData := $configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ $.Values.namespace | default "default"}}
data:
  {{- range $key, $value := $configMapData.data | default dict }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}