{{- range $configmap := .Values.configmaps }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  namespace: {{ $.Values.namespace }}
data:
  {{- range $data := $configmap.data }}
  {{ $data }}
  {{- end }}
{{- end }}