namespace: dev

'nginx-a':
  replicaCount: 1
  ingressHost: hello2.example
  image:
    tag: "1.23.1"

'nginx-b':
  replicaCount: 1
  image:
    tag: "1.23.1"

configmaps:
  - name: google.config
    data: 
      goog_URL: "www.google.com"
      goog_port: "443"

  - name: app.config
    data: 
      FORCE_AP_2FA: "false"
      use_tls: "true"