apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ index .Values "nginx-a" "replicaCount" }}
  selector:
    matchLabels:
      app: nginx-a
  template:
    metadata:
      labels:
        app: nginx-a
    spec:
      containers:
      - name: nginx
        image: {{ index .Values "nginx-a" "image" "name" }}:{{ index .Values "nginx-a" "image" "tag" }}
        ports:
        - containerPort: 80