apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nginx-a
    namespace: {{ .Values.namespace }}
spec:
    ingressClassName: nginx
    rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
                name: web
                port:
                    number: 80