apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
  revisionHistoryLimit: 1