apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.'nginx-b'.replicaCount }}
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.nginx-b.image.tag }}
        ports:
        - containerPort: 80