# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx
#   namespace: {{ .Values.namespace }}
# spec:
#   rules:
#   - host: "{{ .Values.host }}"
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx
#             port:
#               number: 80