{{- range .Values.environments }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  sources:
    {{- range .services }}
    - repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
      name: {{ .name }}-{{ .services.name }}
      path: charts/{{ .name }}
      targetRevision: HEAD
      helm:
        valueFiles:
        - {{ .helmValuesFile }}
      {{- end }}
  destination:
    name: in-cluster
    namespace: {{ .name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}