{{- range $project := .Values.projects }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project.name }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---

{{- range .services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ $project.name }}
  source:
    repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
    path: charts/{{ .name }}
    targetRevision: HEAD
    helm:
      valueFiles:
      - {{ .helmValuesFile }}
  destination:
    name: in-cluster
    namespace: {{ .name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}