{{- range .Values.environments }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  sources:
    {{- range .services }}
    - repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
      path: charts/{{ .name }}
      targetRevision: HEAD
      helm:
        valueFiles:
        - {{ .helmValuesFile }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}