{{- range $project := .Values.environments }}

{{- range .services }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $project.name }}-{{ .name }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ $project.name }}-{{ .name }}=briand52/{{ .name }}
    argocd-image-updater.argoproj.io/{{ $project.name }}-{{ .name }}.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/{{ $project.name }}-{{ .name }}.tag: regex
    argocd-image-updater.argoproj.io/{{ $project.name }}-{{ .name }}.allow-tags: regexp:^{{ $project.name }}-[0-9]+$
    
    argocd-image-updater.argoproj.io/write-back-method: git
    
  labels:
    environment: nonprod
spec:
  project: {{ $project.name }}
  source:
    repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
    path: charts/{{ .name }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/environments/core/{{ .name }}.yaml
        - ../../values/environments/{{ $project.name }}/{{ $project.name }}.yaml
        - ../../values/environments/{{ $project.name }}/{{ .name }}.yaml
  destination:
    name: in-cluster
    namespace: {{ $project.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}