{{- range $project := .Values.environments }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $project.name }}-config
  namespace: argocd
spec:
  project: {{ $project.name }}
  source:
    repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
    path: charts/configmaps
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/environments/core/core.yaml
        - ../../values/environments/{{ $project.name }}/{{ $project.name }}.yaml
  destination:
    name: in-cluster
    namespace: {{ $project.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}