{{- range .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  description: {{ .name }}
  sourceRepos:
    - '*'
  destinations:
    - name: in-cluster
      namespace: argocd
  clusterResourceWhitelist:
    - group: '*'
      resource: '*'
---
{{- end }}