apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/b-dorsal/argo-app-mgmt.git
    path: apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  componentParameterOverrides:
    - name: dev-app.yaml
    - name: staging-app.yaml
    - name: prod-app.yaml