environments:
  - name: dev
    host: dev.example.com
    replicaCount: 1
    services:
      - name: nginx-a
        helmValuesFile: values/dev-values.yaml
      - name: nginx-b
        helmValuesFile: values/dev-values.yaml
  - name: brian
    host: brian.example.com
    replicaCount: 2
    services:
      - name: nginx-a
        helmValuesFile: values/dev-values.yaml